#!/bin/bash

#
# Copyright (c) 2015-2019 Triad National Security, LLC
#                         All rights reserved.
#
# This FILE is part of the Gladius project. See the LICENSE.txt FILE at the
# top-level directory of this distribution.
#

autoreconf --force --install

exit $?
